### ISSUE TITLE
Make configs TOML-compatible

### ISSUE THREAD

**Issue by EmilySeville7cfg** [srsudar/eg#92]
For instance instead of:

```toml
[eg-config]
examples-dir = ~/examples-dir
custom-dir = ~/my/fancy/custom/dir
```

write:

```toml
[eg-config]
examples-dir = "~/examples-dir"
custom-dir = "~/my/fancy/custom/dir"
```
